### ISSUE TITLE
Comparison to RustDDS

### ISSUE THREAD

**Issue by samcarey** [s2e-systems/dust-dds#165] opened 2023-08-28 19:50 UTC
Hi! This looks like a really cool project! Thanks for sharing it!

I did notice that there's another Rust implementation of DDS, [RustDDS](https://github.com/jhelovuo/RustDDS) and I'm trying to decide which one to use, so I'd like to suggest that you clarify the important technical and non-technical differences between these projects so that developers like me know how to choose. I've seen some projects post an FAQ right on their main README for visibility to newcomers.

Specifically, my questions right now are:
- What is motivating this development effort separate from RustDDS? Why not just contribute to a that project, or a fork?
- What are S2E Systems long term support intentions for this project?
- What is the currently implemented set of DDS features, what's not implemented, and what's planned to be implemented. 

I also noticed that y'all haven't had any issues yet, so I thought I'd kick things off for you 😄

**Comment by jrebelo** [comment] 2023-08-29 12:17
Hi @samcarey and thank for your questions and opening the very first issue for DustDDS.

Regarding your questions:
- Our intention when we started developing DustDDS was to have this library as a stable building block that we can use to construct other applications as part of our business. For S2E Systems we decided that the best route in the long run was having both control over the code base and detailed knowledge within our company of the implementation details. Eventually we decided to make our DDS implementation open source since we believe this can be helpful for other developers and would give us both more visibility as well as a higher quality library to build upon.
- As we use DustDDS as the building block for some of our applications the idea is to keep developing and supporting it for the long run in an open-source way.
- The goal of DustDDS is to support the Minimal DDS profile as defined in the OMG standard. At the moment all the basic functionality for publishing and subscribing is in place (discovery, listeners, history QoS and so on). If anything in the minimal profile is not working should be regarded as a bug and will be fixed. 

Regarding the comparison with RustDDS I believe a good way to get an overview would be to compare the [RustDDS examples](https://github.com/jhelovuo/RustDDS/blob/master/examples/shapes_demo/main.rs) and the [DustDDS examples](https://github.com/s2e-systems/dust-dds/blob/master/dds/examples/hello_world_publisher.rs). In both cases, the starting point is the OMG standard DDS API. While the function names and arguments are somewhat similar it seems that we have taken a more strict approach to staying as close as possible to the methods and arguments defined in the standard while RustDDS accepted a larger deviation. From looking over the examples I can see a few other different design choices:

1. DustDDS provides a synchronous API with the asynchronous (event-based) functionality provided using the standard DDS listener mechanism. RustDDS seems to have opted for async function on the user facing API.
2. In DustDDS we have opted to have additional traits on the types to determine the key and representation used. On RustDDS that seems to be achieved by having additional generics on the reader/writer type.
3.  This is probably only of importance if you are considering using other implementations/programming languages but DustDDS has an idl generator which allows you to get the types from an idl file which can be used also in other DDS implementations, in particular the C-based ones.

Both implementations will be able to communicate with each other since they use RTPS as the wire protocol. Also in both cases _serde_ seems to be the library of choice for providing the serialize/deserialize functionality.

I hope this additional information is helpful for you. We will keep this issue open for now while we consider what of this information could be added to the README to help other developers.

**Comment by samcarey** [comment] 2023-08-29 19:59
Awesome! Your reply inspires confidence!

Is this project generally open to 3rd party submitted issues/bug-reports/feature-suggestions and pull requests?

**Comment by jrebelo** [comment] 2023-08-30 19:43
We are definitely open and happy to receive 3rd party issues, bug reports and feature suggestions. For pull requests we are likely not to accept them right now for code copyright reasons. We also provide consultancy services at S2E so we are happy to discuss any requests for professional support to other companies.

**Comment by samcarey** [comment] 2023-08-30 21:09
Ok cool. I think [your license (paragraph 5)](https://github.com/s2e-systems/dust-dds/blob/master/LICENSE) says it will be automatically applied to any 3rd-party contributions (PRs), but I'm no legal expert 😄

**Comment by jrebelo** [comment] 2023-12-07 15:32
We were once more revisiting this question and we after analyzing the examples of both implementation the development directions are different enough to not require special comparison. So the issue is closed as not planned for now.

**Closed by jrebelo** 2023-12-07 15:32 UTC
